#!/bin/bash

###########################################
#                                         #
#   Jean Mercadier (jmercadier.fr)        #
#   new - https://github.com/Ricain/new   #
#   MIT License                           #
#                                         #
###########################################


loc=~/.new
default=index.sh

if [[ $# -lt 1 ]]; then
	echo "new: error: missing arguments"
	exit 1
fi

filename=$1
extension="${1##*.}"

if [[ ! -z $2 ]]; then
	extension=$2
fi

let "exist=0"

for fichier in `ls $loc`; do
	if [[ $fichier = $extension ]]; then
		let "exist+=1"
	fi
done
if [[ $exist -ne 1 ]]; then
	echo "new: error: $extension: file type not registered"
	exit 2
fi

for fichier in `ls`; do
	if [[ $fichier = "$filename" ]]; then
		let "exist-=1"
	fi
done
if [[ $exist -ne 1 ]]; then
	echo "new: error: $filename: file already exist"
	exit 3
fi

$loc/$extension/$default $filename $loc/$extension
